eca/urls.py
from django.contrib import admin
from django.urls import path,include
from eca import settings
from django.conf.urls.static import static,__dict__
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecadmin/',include('ecaadmin.urls')),
    # path('admin', RedirectView.as_view(url=reverse_lazy('admin:index'))),
    # path('systemadmin/', admin.site.urls,name="admin_login"),
    #socialmedialogin url
    # path('oauth/', include('social_django.urls', namespace='social')), 
    # path('saccount/',include('allauth.urls'),name='saccount'),    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('chat/', include('chat.urls'),name='chat'),
    path('', include("front.urls")),
    # path('customer_lms/', include("customer_lms.urls")),
    # path('staff_lms/', include("staff_lms.urls")),
    # path('counsellor/', include("counsellor.urls")),
    path('accounts/', include("accounts.urls")),
    path('account/', include("django.contrib.auth.urls")),

    #Rest Framework Urls
    path('api/front/',include("front.api.urls")),
    path('api/accounts/',include("accounts.api.urls")),
    path('api/cart/',include("cart.api.urls")),
    path('api/discount/',include("discount.api.urls")),

    #password reset and change
    path('password_change/done',auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),name='password_change_done'),
   
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name='password_change.html'),name='password_change'),

    path('password_reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),

    path('reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    
    # url(r'^api/v1/account/', include(('rest_accounts.urls', 'restprofile'), namespace='rest_accounts')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecaadmin/urls.py
from django.urls import path
from ecaadmin import views

urlpatterns = [
    path('', views.admin_home,name='admin_home'),    
    # path('category_list', views.ProductCategoryListViews.as_view(),name='category_list'),
    path('category_list', views.ProductCategoryTabListViews.as_view(),name='category_tab_list'),
    path('category_active/<slug:pk>', views.activeCategory,name='category_active'),
    path('category_deactive/<slug:pk>', views.deactiveCategory,name='category_deactive'),
    path('category_create', views.ProductCategoryCreate.as_view(),name='category_create'),
    path('category_update/<slug:pk>', views.ProductCategoryUpdate.as_view(),name='category_update'),
    
    path('delete_category', views.DeleteAll,name='delete_category'),

    
    path('subcategory_list1', views.ProductSubCategoryListViews.as_view(),name='subcategory_list'),
    path('subcategory_list', views.ProductSubCategoryTabListViews.as_view(),name='subcategory_tab_list'),
    path('subcategory_active/<slug:pk>', views.activeSubCategory,name='subcategory_active'),
    path('subcategory_deactive/<slug:pk>', views.deactiveSubCategory,name='subcategory_deactive'),
    path('subcategory_create', views.ProductSubCategoryCreate.as_view(),name='subcategory_create'),
    path('subcategory_update/<slug:pk>', views.ProductSubCategoryUpdate.as_view(),name='subcategory_update'),
    
    path('childsubcategory_list', views.ProductChildSubCategoryListViews.as_view(),name='childsubcategory_list'),
    path('childsubcategory_tab_list', views.ProductChildSubCategoryTabListViews.as_view(),name='childsubcategory_tab_list'),
    path('childsubcategory_active/<slug:pk>', views.activeChildSubCategory,name='childsubcategory_active'),
    path('childsubcategory_deactive/<slug:pk>', views.deactiveChildSubCategory,name='childsubcategory_deactive'),
    path('childsubcategory_create', views.ProductChildSubCategoryCreate.as_view(),name='childsubcategory_create'),
    path('childsubcategory_update/<slug:pk>', views.ProductChildSubCategoryUpdate.as_view(),name='childsubcategory_update'),
    
    # Merchant
    path('merchant_list', views.MerchantUserListViews.as_view(),name='merchant_list'),
    path('merchant_tab_list', views.MerchantUserTabListViews.as_view(),name='merchant_tab_list'),
    path('merchant_active/<slug:pk>', views.activeMerchant,name='merchant_active'),
    path('merchant_deactive/<slug:pk>', views.deactiveMerchant,name='merchant_deactive'),
    path('merchant_create', views.MerchantUserCreateView.as_view(),name='merchant_create'),
    path('merchant_update/<slug:pk>', views.MerchantUserUpdate.as_view(),name='merchant_update'),
    
    # Product
    path('product_list', views.ProductListViews.as_view(),name='product_list'),
    path('product_tab_list', views.ProductTabListViews.as_view(),name='product_tab_list'),
    path('product_create', views.ProductView.as_view(),name='product_view'),
    path('add_product', views.AddProductView.as_view(),name='add_product'),
    path('product_active/<slug:pk>', views.activeProduct,name='product_active'),
    path('product_deactive/<slug:pk>', views.deactiveProduct,name='product_deactive'),
    path('product_update/<str:product_id>', views.ProductUpdate.as_view(),name='product_update'),
    path('product_new_update/<str:product_id>', views.ProductNewUpdate.as_view(),name='product_new_update'),
    path('product_add_media/<str:product_id>', views.ProductAddMedia.as_view(),name='product_add_media'),
    path('product_edit_media/<str:product_id>',views.ProductEditMedia.as_view(),name="product_edit_media"),
    path('product_media_delete/<str:id>',views.ProductMediaDelete.as_view(),name="product_media_delete"),
    path('product_add_stocks/<str:product_id>',views.ProductAddStocks.as_view(),name="product_add_stocks"),
    path('file_upload', views.file_upload,name='file_upload'),

    #Add Exlusive products
    path('add_exclusive',views.AddExclusive,name="add_exclusive"),

    #Coupons List, Add ,delete
    path('add_delivery_cost',views.DeliveryCostView.as_view(),name="add_delivery_cost"),
    path('delete__delivery_cost/<id>',views.deleteDeliveryCostView,name="delete__delivery_cost"),

    #order list
    path('order_list',views.OrderListView.as_view(),name="order_list"),
    path('admin_order_details/<id>',views.OrderDetailView.as_view(),name="admin_order_details"),
    path('admin_order_update/<id>',views.OrderUpdateView.as_view(),name="admin_order_update"),
    path('admin_order_print/<id>',views.adminOrderPrint,name="admin_order_print"),
    path('admin_shipping_print/<id>',views.adminShippingPrint,name="admin_shipping_print"),


    #Staff User
    path('staff_create',views.StaffUserCreateView.as_view(),name="staff_create"),
    path('staff_list',views.StaffUserListView.as_view(),name="staff_list"),
    path('staff_update/<slug:pk>',views.StaffUserUpdateView.as_view(),name="staff_update"),

    #GST Details
    path('gst_create',views.GstCreateView.as_view(),name="gst_create"),
    path('gst_delete/<slug:pk>',views.gstDelete,name="gst_delete"),

    #Customer User
    path('customer_create',views.CustomerUserCreateView.as_view(),name="customer_create"),
    path('customer_list',views.CustomerUserListView.as_view(),name="customer_list"),
    path('customer_update/<slug:pk>',views.CustomerUserUpdateView.as_view(),name="customer_update"),

]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from django.db import models
from django.db.models.fields import AutoField
from django.db.models.signals import post_save
from django.dispatch import receiver
from front.compression import CompressedImageField
# from ckeditor_uploader.fields import RichTextUploadingField
from rest_framework.authtoken.models import Token
from django.conf import settings
from django.core.validators import RegexValidator
from django.db.models import Q
# Create your models here.

# class CustomUser(AbstractUser): 
#     user_type_data=((1,"HOD"),(2,"Staff"),(3,"Customer"))
#     user_type=models.CharField(choices=user_type_data,max_length=10)


class MyAccountManager(BaseUserManager):
    # create _create_user for mobiel number for facebbook and for google and for userid password so it can be solve your all problem regarding social login/auth
    use_in_migrations = True
    def create_user(self, email, username,password=None):
        if not email:
            raise ValueError("User must have an Email Address")
        if not username:
            raise ValueError("User must have an username ")

        user = self.model(
                email=self.normalize_email(email),
                username=username,                
               
            )
        user.is_active= True
        user.set_password(password)
        print(user.username)
        user.save(using=self._db)
        print(user.email)
        return user

    def create_phone_user(self, phone, email):
        if not email:
            raise ValueError("User must have an Email Address")

        user = self.model(
                email=self.normalize_email(email),
                phone =phone       
               
            )
        user.is_active= True
        user.set_password(phone)
        user.username = phone
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password,**extra_fields):
        user = self.create_user(
                email=self.normalize_email(email),
                password=password,
                username=username,
                            
                
            )
        
        # phone = "7801925101"
        user.is_active = True
        # user.is_admin = True
        # user_type="0"
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser): 
    email = models.EmailField(verbose_name="email", max_length=254, unique=True)
    username = models.CharField(max_length=254,unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="date joined" ,auto_now=True)
    # is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    first_name = models.CharField(max_length=254)
    last_name = models.CharField(max_length=254)
    user_type_data=((1,"Admin"),(2,"Staff"),(3,"Customer"),(4 ,"Merchant"))
    user_type=models.CharField(choices=user_type_data,max_length=10)
    phone_regex     = RegexValidator( regex = r'^\+?1?\d{9,10}$', message ="Phone number must be entered in the format +919999999999. Up to 10 digits allowed.")
    phone           = models.CharField('Phone',validators =[phone_regex], max_length=10, unique = True,null=True)
    is_Mobile_Verified      = models.BooleanField(blank=False, default=False)
    is_Email_Verified      = models.BooleanField(blank=False, default=False)
    counter         = models.IntegerField(default=0, blank=False) #OTP counter
    otp_session_id  = models.CharField(max_length=120, null=True, default = "")
    otp              = models.CharField(max_length=120, null=True, default = "")
    profile_pic         =CompressedImageField(null=True, default=None, quality=60,blank=True)
    
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['username',]

    objects = MyAccountManager()

    def __str__(self):
        return self.email
    
    def has_perm(self,perm,obj=None):
        return self.is_superuser

    def has_module_perms(self,app_label):
        return True    

    @property
    def get_photo_url(self):
        if self.profile_pic and hasattr(self.profile_pic, 'url'):
            return self.profile_pic.url
        else:
            return settings.STATIC_ROOT + "eca_admin/img/avatar/avatar-1.png"

class PhoneOTP(models.Model):
    
    # id=models.AutoField(primary_key=True)
    # admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    phone_regex     = RegexValidator( regex = r'^\+?1?\d{9,10}$', message ="Phone number must be entered in the format +919999999999. Up to 14 digits allowed.")
    phone           = models.CharField(validators =[phone_regex], max_length=17, unique = True)
    otp             = models.CharField(max_length=9, blank = True, null=True)
    count           = models.IntegerField(default=0, help_text = 'Number of otp_sent')
    validated       = models.BooleanField(default = False, help_text = 'If it is true, that means user have validate otp correctly in second API')
    otp_session_id  = models.CharField(max_length=120, null=True, default = "")
    username        = models.CharField(max_length=20, blank = True, null = True, default = None )
    email           = models.CharField(max_length=50, null = True, blank = True, default = None) 
    password        = models.CharField(max_length=100, null = True, blank = True, default = None) 

    

    def __str__(self):
        return str(self.phone) + ' is sent ' + str(self.otp)   

class AdminHOD(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    profile_pic = CompressedImageField(null=True, default=None, quality=60,blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()
    
    @property
    def get_photo_url(self):
        if self.profile_pic and hasattr(self.profile_pic, 'url'):
            return self.profile_pic.url
        else:
            return settings.STATIC_ROOT + "eca_admin/img/avatar/avatar-1.png"

class Staffs(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    first_name=models.CharField(max_length=250,default="",null=True)
    last_name=models.CharField(max_length=250,default="",null=True)
    dob=models.DateField(blank=True,null=True)
    address=models.CharField(max_length=50,blank=True,null=True)
    city=models.CharField(max_length=50,blank=True,null=True)
    state=models.CharField(max_length=50,blank=True,null=True)
    country=models.CharField(max_length=50,blank=True,null=True)
    # mobile=models.CharField(max_length=50,blank=True,null=True)
    # qualification=models.CharField(max_length=50,blank=True,null=True)
    # specialist=models.CharField(max_length=50,blank=True,null=True)
    profile_pic=CompressedImageField(null=True, default=None, quality=60,blank=True)
    # about=RichTextUploadingField(blank=True,null=True)
    # is_appiled=models.BooleanField(blank=True,null=True,default=False)
    is_verified=models.BooleanField(blank=True,null=True,default=False)
    # resume=CompressedImageField(null=True, default=None, quality=60,blank=True)
    # experience=models.CharField(max_length=50,blank=True,null=True)
    # working_with=models.CharField(max_length=50,blank=True,null=True)
    # website=models.URLField(max_length=200,blank=True,null=True)
    # linkdin=models.URLField(max_length=200,blank=True,null=True)
    gender=models.CharField(max_length=200,blank=True,null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)

    objects=models.Manager()
    
    def __str__(self):
        return self.first_name  
    
    @property
    def get_photo_url(self):
        if self.profile_pic and hasattr(self.profile_pic, 'url'):
            return self.profile_pic.url
        else:
            return settings.STATIC_ROOT + "eca_admin/img/avatar/avatar-1.png"

            
class Customers(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    fisrt_name=models.CharField(max_length=250,blank=True,null=True)
    last_name=models.CharField(max_length=250,blank=True,null=True)
    address=models.CharField(max_length=500,blank=True,null=True)
    city=models.CharField(max_length=250,blank=True,null=True)
    state=models.CharField(max_length=250,blank=True,null=True)
    country=models.CharField(max_length=250,blank=True,null=True)
    zip_Code =models.CharField(max_length=250,blank=True,null=True)
    # qualification =models.CharField(max_length=250,blank=True,null=True)
    dob=models.DateField(blank=True,null=True)
    phone=models.CharField(max_length=250,blank=True,null=True)
    profile_pic=CompressedImageField(null=True, default=None, quality=60,blank=True)
    gender=models.CharField(max_length=255,null=True)
    # is_appiled=models.BooleanField(blank=True,null=True,default=False)
    # is_verified=models.BooleanField(blank=True,null=True,default=False)
    # session_start=models.DateField(null=True)
    # session_end=models.DateField(null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects = models.Manager()
    
    @property
    def get_photo_url(self):
        if self.profile_pic and hasattr(self.profile_pic, 'url'):
            return self.profile_pic.url
        else:
            return settings.STATIC_ROOT + "eca_admin/img/avatar/avatar-1.png"

class CustomersAddress(models.Model):  
    id=models.AutoField(primary_key=True)

ecaadmin/templates/ecaadmin/category_create.html
{% extends 'ecaadmin/admin_base.html' %}

{% block title %} Category Create{% endblock title %} 


{% block page_content %}

<div class="raw">
<div class="col-12 col-md-12 col-lg-12">
    <div class="card">
        <div class="card-header">
        <h4>Add Cetegory</h4>
        </div>
        <div class="card-body">
          
            
        <form method="post", enctype = "multipart/form-data">
        {% csrf_token %}
        
        {% for field in form %}
        <div class="form-group">
            {% if field.field.widget.input_type != "checkbox" %}
            <label>{{ field.label}}</label>
            <input type="{{field.field.widget.input_type}}" name={{field.name}} id="{{field.name}}" class="form-control">
            
            {% else %}
            <label class="custom-switch mt-2">
                <input type="checkbox" name="is_active" id ="is_active" class="custom-switch-input" value="True">
                <span class="custom-switch-indicator"></span>
                <span class="custom-switch-description">Is_active</span>
            </label> 
            {% endif %}
        

            {% if field.errors %}
                <div class = "alert alert-danger" style ="margin:10px;">
                {{field.errors }}
                </div> 
            {% endif %}
        </div>
        {% endfor %}
        <button href = "#" class = "btn btn-primary btn-block" type="submit" > SAVE CATEGORY</button>    
    </div>
</div>
</div>
                


    


{% endblock page_content %}


{% block custom_js %}

{% endblock custom_js %}

ecaadmin/templates/ecaadmin/category_update.html
{% extends 'ecaadmin/admin_base.html' %}

{% block title %} Category Create{% endblock title %} 


{% block page_content %}

<div class="raw">
<div class="col-12 col-md-12 col-lg-12">
    <div class="card">
        <div class="card-header">
        <h4>Cetegory Update </h4>
        </div>
        <div class="card-body">
          
            
        <form method="post", enctype = "multipart/form-data">
        {% csrf_token %}
       
        {% for field in form %}
        <div class="form-group">
            {% if field.field.widget.input_type == "checkbox" %}
            <div class="article-cta">
                <label class="custom-switch mt-2" style="float:center">
                        <input type="checkbox" name="{{field.name}}" class="custom-switch-input update" id="{{field.name}}" {% if field.value == True %}checked{% endif %}> 
                        <span class="custom-switch-indicator"></span>
                        <span class="custom-switch-description">ACTIVE</span>
                </label>
            </div>              
            {% else %}            
                <label>{{ field.label}}</label>
                <input type="{{field.field.widget.input_type}}" name={{field.name}} id="{{field.name}}" class="form-control" value = "{{field.value}}">
                <div class="form-group">
            
              
            {% endif %}
            
            {% comment %} {% if field.field.widget.input_type == "select" %}
            <label>{{ field.label}}</label>
                <select  name={{field.name}} id="{{field.name}}" class="form-control" >
                    <option >select</option>
                {% for id,value in field.field.choices %}
                    {% if value == field.value  %}
                    <option value="{{id}}"selected >{{value}}</option>
                    
                    {% endif %}
                    <option value="{{id}}">{{value}}</option>
                {% endfor %}
                </select>
            
            {% endif %} {% endcomment %}
            {% if field.errors %}
                <div class = "alert alert-danger" style ="margin:10px;">
                {{field.errors }}
                </div>                

            {% endif %}
        </div>
        
        {% endfor %}
        <button href = "#" class = "btn btn-primary btn-block" type="submit" > SAVE CATEGORY</button>    
    </div>
</div>
</div>
                


    


{% endblock page_content %}


{% block custom_js %}
<script>
//function myFunction() {
{% comment %} $('.update').on("click", function(){
    var checkBox = document.getElementById("myCheck");
    var form=new FormData($("#myform")[0]);
    if (checkBox.checked == true){
        console.log("inside if")
        open("POST","{% url 'category_active' category.id %}",true);
    } else {
        open("POST","{% url 'category_deactive' category.id %}",true);
    }
    xhr.send(form);
})
  
} {% endcomment %}
</script>
{% endblock custom_js %}

ecaadmin/templates/ecaadmin/childsubcategory_update.html
{% extends 'ecaadmin/admin_base.html' %}

{% block title %} sub Category Update{% endblock title %} 


{% block page_content %}

<div class="raw">
<div class="col-12 col-md-12 col-lg-12">
    <div class="card">
        <div class="card-header">
        <h4>Cetegory Update </h4>
        </div>
        <div class="card-body">
          
            
        <form method="post", enctype = "multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>Category</label>
                <select name="sub_category" class="form-control">
                    {% for category in categories  %}
                        <optgroup label={{ category.category.title}}>
                        {% for sub_cat in category.sub_category  %}
                            <option value="{{ sub_cat.id }}" {% if sub_cat.id == pchsbct.subcategory.id %} selected {% endif %}>{{sub_cat.title}}</option>
                        {% endfor %}   
                        </optgroup>     
                    {% endfor %}
                </select>
        </div>
        <div class="form-group">
            <label>Name</label>
            <input class="form-control" name="title" placeholder="Child Sub Category" id="title" value="{{ pchsbct.title }}"/>
        </div>
        <div class="form-group">
        <label>Thumbnail</label>
        <input type="file" class="form-control" name="thumbnail" placeholder="thumbnail" id="thumbnail" value="{{ pchsbct.get_thumbnail_url}}"/> <br>
        <div class="card">   
                <label>Thumbnail</label>     
                <div class="card-body">
                <img src="{{pchsbct.get_thumbnail_url}}" style = "height:150px"/>
                </div>
                
        </div>
        </div>

        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="description" placeholder="description" id="title" value="{{ pchsbct.description }}"/>
        </div>
        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="is_active" placeholder="is_active" id="is_active" value="{{ pchsbct.is_active }}"/>
        </div>


     
               
        
        <button href = "#" class = "btn btn-primary btn-block" type="submit" > SAVE CHILD SUB CATEGORY</button>    
    </div>
</div>
</div>
                


    


{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}

ecaadmin/templates/ecaadmin/customer_create.html
{% extends 'ecaadmin/admin_base.html' %}
{% block title %}
Customer Create
{% endblock title %}


{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Customer Create
{% endblock page_title %}

{% block page_content %}

<div class="row">
<div class="col-12 col-md-12 col-lg-12">
<div class="card">
    <div class="card-header">
    <h4>Customer Users</h4>
    </div>
    <div class="card-body">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label>{{ field.label }}</label>
            <input type="{{ field.field.widget.input_type }}" name={{ field.name }} id="{{ field.name }}" class="form-control">
            {% if field.errors %}
            <div class="alert alert-danger" style="margin:10px">
                {{ field.errors }}
            </div>
            {% endif %}
        </div>
        {% endfor %}
         <div class="form-group">
            <label>Profile Image</label>
            <input type="file" name="profile_pic" id="profile_pic" class="form-control">
        </div>

  


        <button type="submit" class="btn btn-primary btn-block">SAVE CUSTOMER USER</button>
    </form>
</div>
</div>
</div>
</div>
{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}

ecaadmin/templates/ecaadmin/customer_list.html
{% extends 'ecaadmin/admin_base.html' %}
{% block title %}
Customer User List
{% endblock title %}


{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Customer User List
{% endblock page_title %}

{% block page_content %}
<div class="row">
    <div class="col-lg-12">
        <div class="search-element">
        <div class="card">
                  
                  <div class="card-body">
                  <form method="get">
                    <button class="btn  btn-primary" type="submit" style="float:right"><i class="fas fa-search"></i> Search</button>
                    <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250" style="width: 250px;float:right" name="filter" value="{{ filter }}">
                   </form>
                  </div>
                  
                </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="search-element">
        <div class="card">
                  
            <div class="card-body">
                <b>Sort By : - </b>
                <a href="{% url 'customer_list' %}?filter={{ filter }}&orderby=id">ID</a>  | 
                <a href="{% url 'customer_list' %}?filter={{ filter }}&orderby=created_at">Newest</a> |  
                <a href="{% url 'customer_list' %}?filter={{ filter }}&orderby=auth_user_id__first_name">First Name</a> |
                <a href="{% url 'customer_list' %}?filter={{ filter }}&orderby=auth_user_id__username">Username</a> |
            </div>
        </div>
        </div>
    </div>
</div>
<div class="row">
{% for customeruser in customers_list %}
<div class="col-12 col-sm-6 col-md-6 col-lg-3">
    <article class="article article-style-b">
        <div class="article-header">
        <div class="article-image" data-background="{{ customeruser.get_photo_url }}" style="background-image: url(&quot;{{customeruser.get_photo_url}}&quot;);">
        </div>
        <div class="article-badge">
            <div class="article-badge-item bg-danger"><i class="fas fa-fire"></i>{{ customeruser.admin.username }}</div>
        </div>
        </div>
        <div class="article-details">
        <p class="no-margin"><span class="badge badge-warning"><i class="fas fa-user-circle"></i> Name : {{ customeruser.admin.first_name }} {{ customeruser.admin.last_name }}</span></p>
        <p class="no-margin"><span class="badge badge-info"><i class="fas fa-envelope-o "></i> Email : {{ customeruser.admin.email }}</span></p>
        <div class="article-cta">
            <label class="custom-switch mt-2" style="float:left">
                        <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input" {% if customeruser.admin.is_active == 1 %}checked{% endif %}>
                        <span class="custom-switch-indicator"></span>
                        <span class="custom-switch-description">ACTIVE</span>
            </label>
            <a href="{% url 'customer_update' customeruser.admin.id %}" class="btn btn-warning">EDIT <i class="fas fa-chevron-right"></i></a>
        </div>
        </div>
    </article>
</div>
{% endfor %}
</div>
<div class="row">
<div class="col-lg-12">
<div class="card">
                 
                  <div class="card-body">
                    <nav aria-label="Page navigation example">
                      <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="{% url 'customer_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                                <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link" href="{% url 'customer_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="{% url 'customer_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        {% endif %}

                      </ul>
                    </nav>
                  </div>
                </div>
                </div>
</div>
{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}